services:
  postgres:
    image: postgres:16-alpine
    container_name: matcha-time-postgres
    environment:
      POSTGRES_USER: matcha_user
      POSTGRES_PASSWORD: matcha_password
      POSTGRES_DB: matcha_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matcha_user -d matcha_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

